services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: psiplanner-db
      POSTGRES_USER: psiplanner
      POSTGRES_PASSWORD: psiplanner
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  springbootapp:
    build: .
    container_name: springbootapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/psiplanner-db
      SPRING_DATASOURCE_USERNAME: psiplanner
      SPRING_DATASOURCE_PASSWORD: psiplanner
      SECURITY_CONST_KEY: ${SECURITY_CONST_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: