CREATE TABLE person
(
    person_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    cpf        VARCHAR(255)                            NOT NULL,
    phone      VARCHAR(255)                            NOT NULL,
    birth_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    gender     VARCHAR(255),
    ethnicity  VARCHAR(255),
    email      VARCHAR(255),
    CONSTRAINT pk_person PRIMARY KEY (person_id)
);

ALTER TABLE "user"
    ADD person_id BIGINT;

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_person UNIQUE (person_id);

ALTER TABLE "user"
    ADD CONSTRAINT FK_USER_ON_PERSON FOREIGN KEY (person_id) REFERENCES person (person_id);

ALTER TABLE "user"
    DROP COLUMN email;