ALTER TABLE "user"
    DROP CONSTRAINT fk_user_on_person;

ALTER TABLE user_roles
    DROP CONSTRAINT fk_userol_on_user;

CREATE TABLE users
(
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username  VARCHAR(255)                            NOT NULL,
    password  VARCHAR(255)                            NOT NULL,
    person_id BIGINT,
    active    BOOLEAN,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_person UNIQUE (person_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_PERSON FOREIGN KEY (person_id) REFERENCES person (person_id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (user_id);

DROP TABLE "user" CASCADE;